name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate JSON Resume
        uses: lukew3/validate-json-resume-action@main
        with:
          resume_path: resume.json
      
      - name: Json to tex
        uses: lukew3/json-fill-erb-action@main
        with:
          json_path: resume.json
          erb_path: template.tex.erb
          out_path: resume.tex

      - uses: actions/upload-artifact@v4
        with:
          path: resume.tex

      - name: tex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: resume.pdf
          asset_name: ${{ github.actor }}_resume.pdf
          asset_content_type: application/pdf

